namespace Assets.Scripts.Enumerables
{
    public enum SubType
    {
        Air,
        Amphibious,
        Aquatic,
        Chimera,
        Colossal,
        Construct,
        DemiGod,
        Demonic,
        Earth,
        Fire,
        Giant,
        Holy,
        Horned,
        Land,
        Large,
        Lich,
        Lightning,
        Minitature,
        Monstrous,
        MultiLimbed,
        Mystic,
        Natural,
        Pygmy,
        Shadow,
        Skeletal,
        Small,
        Stingered,
        Stone,
        Vampire,
        Water,
        Were,
        Winged,
        Zombie
    }
}
